services:
  bot:
    build: .
    depends_on:
      database:
        condition: service_healthy
  
  database:
    image: postgres:18
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./pg_hba.dev.conf:/etc/pg_hba.conf
    command: -c hba_file=/etc/pg_hba.conf
    healthcheck:
      test:
        - CMD-SHELL
        - 'pg_isready -U postgres'

volumes:
  postgres_data:
